### ISSUE TITLE
Huge blank space on page: documentation/node/handsonnode/00-preface.html.md

### ISSUE THREAD

**Issue by alexwoehr** [bevry/documentation#23]
There is a huge section of blank space in file documentation/node/handsonnode/00-preface.html.md. ([Rendered page](https://learn.bevry.me/node/preface)). If you assign me, I can get around to looking at this and producing a pull request to eliminate the blank space.

- Browser: Chrome 41
- OS: Linux / Fedora 20

**Comment by mikeumus** [comment]
Hey @alexwoehr, the help is most welcomed. Yeah the docpad.org site's doc need a little repair here and there as you're noticing. I can only assign things to members of the GitHub DocPad Org, but you can still fork the DocPad website repo, run it locally, fix the issue and then submit a pull request. We will be sure to give you credit for the pull request and list you in the Contributors and anywhere else applicable.

**Comment by alexwoehr** [comment]
You are right -- I just realized that I should be creating issues on my
branch, probably, until I submit a pull request. None of the issues I have
created thus far really need that much input from you.

**Comment by mikeumus** [comment]
Well no, it's good that you report them. That way if anyone else goes looking here, they'll find our conversation and know it's recent and that you're looking into it. You're definitely not spamming, feel good about it. :heart_decoration::+1:

**Comment by balupton** [comment]
This is probably resolved.
